### PR TITLE
Comment added

### PR DESCRIPTION
**Pull request by pepicrft**
- I have added a new comment into code

### CODE REVIEW

**Comment by sergigracia** [comment]
Awesome feature :trollface:

hehe it's ok :+1:

**Comment by pepicrft** [comment]
Yes, jajajaj, many users asked for it xD @sergigracia

**Comment by isaacroldan** [comment]
:+1: cool!, let's merge! :hankey:

**Comment by pepicrft** [comment]
:ok_hand:

**Pull request merged**
